const DATA_REQUESTED = 'DATA_REQUESTED';
const DATA_LOADED = 'DATA_LOADED';
const DATA_ERROR = 'DATA_ERROR';
const BAD_DATA_FOUND = 'BAD_DATA_FOUND';

export {
  DATA_REQUESTED,
  DATA_LOADED,
  DATA_ERROR,
  BAD_DATA_FOUND
};